FROM node:12.18.1-alpine              

WORKDIR /usr/src/app                  

COPY /app/package*.json ./                 

CMD npm config set cache-min 9999999 && \    
    npm install && \              
    npx wait-port mysql:3306 && \           
    npm run start:dev      

